[build.environment]
  REACT_APP_PROD_ETHEREUM_PROVIDER="http://localhost:8545"
  REACT_APP_PROD_KOVAN_ARBITRATOR_ADDRESS="0x7a5a9d8235a7bd3cd75adc8f1089c51da113b2cc"
  REACT_APP_PROD_RINKEBY_ARBITRATOR_ADDRESS="0x27a836a66a16d10a4d5a400dd89417e4e9a8961f"
  REACT_APP_PROD_MAINNET_ARBITRATOR_ADDRESS="0xa9f0ed953257de9598523c04741adc8225c9b1c5"
  REACT_APP_PROD_STORE_PROVIDER="https://develop.kleros.in"
  REACT_APP_PROD_DOGE_IMAGES_BASE_URL="https://staging-doges-on-trial-doge-images.s3.us-east-2.amazonaws.com/"

[context.production.environment]
  REACT_APP_PROD_ETHEREUM_PROVIDER="<provider>"
  REACT_APP_PROD_KOVAN_ARBITRATOR_ADDRESS="0x6183694b0f853dff99cde9ad322973ac580b2127"
  REACT_APP_PROD_RINKEBY_ARBITRATOR_ADDRESS="0xcafa054b1b054581faf65adce667bf1c684b6ef0"
  REACT_APP_PROD_MAINNET_ARBITRATOR_ADDRESS="0xa9f0ed953257de9598523c04741adc8225c9b1c5"
  REACT_APP_PROD_STORE_PROVIDER="https://kleros.in"
  REACT_APP_PROD_DOGE_IMAGES_BASE_URL="https://production-doges-on-trial-doge-images.s3.us-east-2.amazonaws.com/"
