[build.environment]
  REACT_APP_PROD_ARBITRATOR_ADDRESS = "0x3af76ef44932695a33ba2af52018cd24a74c904f"

[context.production.environment]
  REACT_APP_PROD_ARBITRATOR_ADDRESS = "0xA2D6CC4eCec4B1189F61dF4dD0a4FE06dfad0dEc"
